apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-elasticsearch
  template:
    metadata:
      labels:
        app: camunda-elasticsearch
    spec:
      containers:
      - name: elasticsearch-container
        image: docker.elastic.co/elasticsearch/elasticsearch:latest
        ports:
        - containerPort: 9200