apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: camunda-elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: LoadBalancer  # Use LoadBalancer if running on a cloud provider