apiVersion: v1
kind: Service
metadata:
  name: operate-service
spec:
  selector:
    app: camunda-operate
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer