apiVersion: v1
kind: Service
metadata:
  name: zeebe-service
spec:
  selector:
    app: camunda-zeebe
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer  # Use LoadBalancer if running on a cloud provider
